config/routes.rb
Rails.application.routes.draw do

  root to: 'ocr_images#new'

  resources :ocr_images do
    collection do
      post :destroy_all
    end
  end

end

app/models/ocr_image.rb
require 'image_bucket'
require 'mime/types'
require 'ocrable'

class OcrImage < ActiveRecord::Base

  include Ocrable

  before_destroy :clean_up_s3


  def url
    image_bucket.url(id)
  end

  def process!
    update_attributes content: ocr_text_for_file
  end

  def self.upload(file)
    create!.tap do |image|
      image.upload(resized_image(File.open(file.path).read), file.content_type)
    end
  end

  def upload(file, content_type)
    image_bucket.put(id, file, content_type)
  end

  private

  def clean_up_s3
    image_bucket.destroy(id)
  end

  def image
    data
  end

  def data
    image_bucket.body(id)
  end

  def filename
    "#{id}.#{file_extension}"
  end

  def image_bucket
    @image_bucket ||= ImageBucket.new
  end

  def content_type
    image_bucket.content_type(id)
  end

  def file_extension
    MIME::Types[content_type].first.extensions.first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def show
    @ocr_image = OcrImage.find(params[:id])
  end

  def new
    @ocr_image = OcrImage.new
  end

  def create
    @ocr_image = OcrImage.upload image_params[:file]
    @ocr_image.process!
    flash[:alert] = "Image created"
    redirect_to image_path(@ocr_image)
  end

  private

  def image_params
    params.require(:ocr_image).permit(:file)
  end
end

app/controllers/ocr_images_controller.rb
class OcrImagesController < ApplicationController

  def index
    @images = OcrImage.all
  end

  def show
    @ocr_image = OcrImage.find(params[:id])
  end

  def new
    @ocr_image = OcrImage.new
  end

  def create
    @ocr_image = OcrImage.upload image_params[:file]
    @ocr_image.process!
    flash[:alert] = "Image created"
    redirect_to ocr_image_path(@ocr_image)
  end

  def destroy_all
    OcrImage.destroy_all
    render :index
  end

  private

  def image_params
    params.require(:ocr_image).permit(:file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ocr</title>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/ocr_images/_ocr_image.html.erb
<%= link_to ocr_image.url do %>
  <image src="<%= ocr_image.url.html_safe %>"/>
<% end %>
<h1><%= ocr_image.content %></h1>

app/views/ocr_images/index.html.erb
<%= link_to "Upload", new_ocr_image_path %>

<% @images.each do |image| %>
  <div>
    <%= render image %>
  </div>
<% end %>

app/views/ocr_images/new.html.erb
<%= form_for @ocr_image, url: ocr_images_path, multipart: true do |form| %>
  <%= form.file_field :file %>
  <%= form.submit %>
<% end %>

app/views/ocr_images/show.html.erb
<%= link_to 'All', ocr_images_path %>

<%= render @ocr_image %>